#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  formatter: stylish
# File Options
files:
  include: '_dev/sass/**/*.scss'
  ignore:
    - '_dev/sass/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 0
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 0
    -
      style: uppercase
  indentation:
    - 0
    -
      size: 2
  property-sort-order:
    - 0
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 0
    -
      properties:
        - margin
        - content
